server:
  port: 80

spring:
  application:
    name: cloud-hystrix-consumer-order

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/

# 设置openfeign服务调用的参数
feign:
  # 设置服务调用启动了hystrix
  hystrix:
    enabled: true