server:
  port: 9527

spring:
  application:
    name: cloud-gateway-gateway
  cloud:
  # 新增网关配置
    gateway:
      # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
      discovery:
        locator:
          enabled: true

      routes:
        #路由的ID，没有固定规则但要求唯一,建议配合服务名
        - id: payment_routh_get
          # 匹配后提供服务的路由地址
          # uri: http://localhost:8001
          # lb表示uri的协议是lb，开启gateway的负载均衡功能
          uri: lb://CLOUD-EUREKA-PAYMENT-SERVICE
          # 断言，路径相匹配的进行路由
          predicates:
          - Path=/payment/getPaymentById/**

        - id: payment_routh_lb
          # uri: http://localhost:8001
          # lb表示uri的协议是lb，开启gateway的负载均衡功能
          uri: lb://CLOUD-EUREKA-PAYMENT-SERVICE
          predicates:
          - Path=/payment/lb/**

eureka:
  instance:
    hostname: cloud-gateway-gateway-service
    prefer-ip-address: true
    instance-id: gateway9527.com
  client:
    service-url:
      register-with-eureka: true
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
      fetch-registry: true
