server:
  port: 7001

eureka:

  server:
    # 出厂默认自我保护机制时开启的，true为开启
    #关闭自我保护机制，保证不可用服务被及时踢除
    enable-self-preservation: false
    # enable-self-preservation: true

  instance:
    hostname: eureka7001.com #eureka服务端的实例名称，在hosts中配置对应网址
    # hostname: localhost #eureka服务端的实例名称
  client:
    #false表示不向注册中心注册自己。
    register-with-eureka: false
    #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址。
      #  defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://eureka7002.com:7002/eureka/ # 构建集群时，相互注册相互守望，所以向7002服务器进行注册