server:
  port: 9527

spring:
  application:
    name: cloud-zuul-gateway

eureka:
  client:
    service-url:
      register-with-eureka: true
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
      # defaultZone: http://eureka7001.com:7001/eureka
  #向eureka注册的实例
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true
    hostname: cloud-gateway-zuul-service